# Generated by Django 5.1.3 on 2024-12-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_workouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "section_order",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sections",
                        to="saved_workouts.workout",
                    ),
                ),
            ],
        ),
    ]
