# Generated by Django 5.1.3 on 2024-12-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout_sections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="section_order",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
