# Generated by Django 5.1.3 on 2025-03-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("movements", "0006_rename_equipment_movement_high_level_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "combo_label",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("equipment", models.ManyToManyField(to="equipment.equipment")),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_combos",
                        to="movements.movement",
                    ),
                ),
            ],
        ),
    ]
