# Generated by Django 5.1.3 on 2025-02-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_hiit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedHIITDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block_name", models.CharField(blank=True, max_length=50, null=True)),
                ("rep_scheme", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "hiit_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiit_details",
                        to="saved_hiit.savedhiitworkout",
                    ),
                ),
            ],
        ),
    ]
