# Generated by Django 5.1.3 on 2025-01-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conditioning_summary", "0001_initial"),
        ("workout_sections", "0003_section_section_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditioningWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conditioning_overview",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_conditionings",
                        to="conditioning_summary.conditioningoverview",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioning_elements",
                        to="workout_sections.section",
                    ),
                ),
            ],
        ),
    ]
