# Generated by Django 5.1.3 on 2025-01-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_conditioning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioningworkout",
            name="comments",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="conditioningworkout",
            name="rpe",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
