# Generated by Django 5.1.3 on 2025-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedWorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_type", models.CharField(blank=True, max_length=50)),
                ("duration", models.PositiveIntegerField(default=0)),
                ("complexity", models.CharField(blank=True, max_length=50)),
                ("finish_type", models.CharField(blank=True, max_length=50)),
                ("strong_1", models.TextField(blank=True)),
                ("strong_2", models.TextField(blank=True)),
                ("build_1", models.TextField(blank=True)),
                ("build_2", models.TextField(blank=True)),
                ("pump_1", models.TextField(blank=True)),
                ("pump_2", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MovementUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("workout_type", models.CharField(blank=True, max_length=50)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
