# Generated by Django 5.1.3 on 2025-04-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movement_workout_tracking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generatedworkoutplan",
            old_name="build_1",
            new_name="build_1_movement_1",
        ),
        migrations.RenameField(
            model_name="generatedworkoutplan",
            old_name="build_2",
            new_name="build_1_movement_2",
        ),
        migrations.RenameField(
            model_name="generatedworkoutplan",
            old_name="pump_1",
            new_name="build_2_movement_1",
        ),
        migrations.RenameField(
            model_name="generatedworkoutplan",
            old_name="pump_2",
            new_name="build_2_movement_2",
        ),
        migrations.AddField(
            model_name="generatedworkoutplan",
            name="pump_1_movement_1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedworkoutplan",
            name="pump_1_movement_2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedworkoutplan",
            name="pump_2_movement_1",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="generatedworkoutplan",
            name="pump_2_movement_2",
            field=models.TextField(blank=True),
        ),
    ]
