# Generated by Django 5.1.3 on 2025-04-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "movement_workout_tracking",
            "0002_rename_build_1_generatedworkoutplan_build_1_movement_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movementusage",
            name="total_workouts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movementusage",
            name="workout_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="movementusage",
            unique_together={("movement", "category", "workout_type", "workout_time")},
        ),
    ]
