# Generated by Django 5.1.3 on 2025-04-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movement_workout_tracking", "0003_movementusage_total_workouts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movementusage",
            name="total_workouts",
        ),
    ]
