# Generated by Django 5.1.3 on 2025-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movement_workout_tracking", "0004_remove_movementusage_total_workouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedworkoutplan",
            name="request_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
