# Generated by Django 5.1.3 on 2025-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("running_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRunningInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_interval", models.PositiveIntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_intervals",
                        to="running_sessions.runningsession",
                    ),
                ),
            ],
        ),
    ]
