# Generated by Django 5.1.3 on 2025-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_run_intervals", "0001_initial"),
        ("saved_runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrunninginterval",
            name="saved_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervals",
                to="saved_runs.savedrunningsession",
            ),
        ),
    ]
