# Generated by Django 5.1.3 on 2025-01-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_run_intervals", "0002_initial"),
        ("saved_runs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedrunninginterval",
            old_name="target_interval",
            new_name="average_actual_pace",
        ),
        migrations.RemoveField(
            model_name="savedrunninginterval",
            name="interval",
        ),
        migrations.AddField(
            model_name="savedrunninginterval",
            name="repeat_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunninginterval",
            name="repeat_variation",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunninginterval",
            name="repeats",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunninginterval",
            name="target_pace",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedrunninginterval",
            name="saved_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_intervals",
                to="saved_runs.savedrunningsession",
            ),
        ),
    ]
