# Generated by Django 5.1.3 on 2025-01-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "saved_run_intervals",
            "0003_rename_target_interval_savedrunninginterval_average_actual_pace_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrunninginterval",
            name="rest_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
