# Generated by Django 5.1.3 on 2025-02-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0002_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exercise_regularity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fitness_goals",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_registration_complete",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="non_negotiable_dislikes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
