# Generated by Django 5.1.3 on 2025-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0003_user_exercise_regularity_user_fitness_goals_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_registration_complete",
        ),
        migrations.AddField(
            model_name="user",
            name="is_onboarding_complete",
            field=models.BooleanField(default=False),
        ),
    ]
