# Generated by Django 5.1.3 on 2025-02-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0004_remove_user_is_registration_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="five_k_mins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="five_k_secs",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
