# Generated by Django 5.1.3 on 2025-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0005_user_five_k_mins_user_five_k_secs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
