# Generated by Django 5.1.3 on 2025-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jwt_auth", "0006_user_expo_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hyrox_division",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
