# Generated by Django 5.1.3 on 2025-04-15 13:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movements", "0012_alter_movement_coaching_cue1_and_more"),
        ("saved_workouts", "0009_remove_workout_hyrox_division"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StrengthSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_date",
                    models.DateField(db_index=True, default=datetime.date.today),
                ),
                ("set_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("reps", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("rpe", models.FloatField(blank=True, null=True)),
                ("load", models.FloatField(blank=True, null=True)),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movements.movement",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="saved_workouts.workout",
                    ),
                ),
            ],
        ),
    ]
