# Generated by Django 5.1.3 on 2025-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strength_records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strengthset",
            name="reps",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="strengthset",
            name="rpe",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="strengthset",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
