# Generated by Django 5.1.3 on 2025-01-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movements", "0005_movement_landscape_thumbnail"),
        ("saved_mobility", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedMobilityDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_details",
                        to="saved_mobility.savedmobilitysession",
                    ),
                ),
                (
                    "movements",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_movement_details",
                        to="movements.movement",
                    ),
                ),
            ],
        ),
    ]
