# Generated by Django 5.1.3 on 2025-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_mobility_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedmobilitydetails",
            name="duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
