# Generated by Django 5.1.3 on 2024-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score_logging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scorelog",
            name="section_movement_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scorelog",
            name="workout_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
