# Generated by Django 5.1.3 on 2025-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConditioningOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("movements", models.PositiveIntegerField()),
                ("rest", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
