# Generated by Django 5.1.3 on 2025-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conditioning_summary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioningoverview",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="conditioningoverview",
            name="movements",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="conditioningoverview",
            name="rest",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
