# Generated by Django 5.1.3 on 2024-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="total_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
