# Generated by Django 5.1.3 on 2025-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaderboard", "0002_alter_leaderboard_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="monthly_rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="total_rank",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="weekly_rank",
            field=models.IntegerField(default=0),
        ),
    ]
