# Generated by Django 5.1.3 on 2024-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_area', models.CharField(blank=True, max_length=15, null=True)),
                ('movement', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise', models.CharField(blank=True, max_length=100, null=True)),
                ('complexity', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('movement_type', models.SmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
