# Generated by Django 5.1.3 on 2024-12-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="primary_body_part",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
