# Generated by Django 5.1.3 on 2024-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0002_movement_primary_body_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="movement_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
