# Generated by Django 5.1.3 on 2025-01-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0003_alter_movement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="equipment",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="landscape_video_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="portrait_video_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
