# Generated by Django 5.1.3 on 2025-01-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0004_movement_equipment_movement_landscape_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="landscape_thumbnail",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
