# Generated by Django 5.1.3 on 2025-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0005_movement_landscape_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="equipment",
            new_name="high_level_equipment",
        ),
        migrations.AddField(
            model_name="movement",
            name="detail_equipment",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="hiit_flag",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="pump_flag",
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
