# Generated by Django 5.1.3 on 2025-03-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0006_rename_equipment_movement_high_level_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="advanced_movements",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
