# Generated by Django 5.1.3 on 2025-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0007_movement_advanced_movements"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="inter_movements",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
