# Generated by Django 5.1.3 on 2025-03-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0008_movement_inter_movements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="inter_movements",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
