# Generated by Django 5.1.3 on 2025-04-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0009_alter_movement_inter_movements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movement",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="detail_equipment",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="high_level_equipment",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="movement_type",
        ),
        migrations.RemoveField(
            model_name="movement",
            name="pump_flag",
        ),
        migrations.AddField(
            model_name="movement",
            name="coaching_cue_1",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="coaching_cue_2",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="movement",
            name="movement_hold_cue",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
