# Generated by Django 5.1.3 on 2025-04-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0010_remove_movement_complexity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movement",
            old_name="coaching_cue_1",
            new_name="coaching_cue1",
        ),
        migrations.RenameField(
            model_name="movement",
            old_name="coaching_cue_2",
            new_name="coaching_cue2",
        ),
    ]
