# Generated by Django 5.1.3 on 2025-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0011_rename_coaching_cue_1_movement_coaching_cue1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="coaching_cue1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="movement",
            name="coaching_cue2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
