# Generated by Django 5.1.3 on 2025-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0012_alter_movement_coaching_cue1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="equipment_check",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
