# Generated by Django 5.1.3 on 2025-01-24 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mobility_overview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilityWorkoutDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise", models.CharField(blank=True, max_length=200, null=True)),
                ("order", models.PositiveIntegerField()),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="mobility_overview.mobilityworkout",
                    ),
                ),
            ],
        ),
    ]
