# Generated by Django 5.1.3 on 2025-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("running_sessions", "0001_initial"),
        ("saved_workouts", "0006_workout_activity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRunningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rpe", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "running_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_sessions",
                        to="running_sessions.runningsession",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_sessions",
                        to="saved_workouts.workout",
                    ),
                ),
            ],
        ),
    ]
