# Generated by Django 5.1.3 on 2025-01-08 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("running_sessions", "0001_initial"),
        ("saved_runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrunningsession",
            name="actual_cooldown_pace",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsession",
            name="actual_warmup_pace",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsession",
            name="suggested_cooldown_pace",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsession",
            name="suggested_warmup_pace",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedrunningsession",
            name="running_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saved_sessions",
                to="running_sessions.runningsession",
            ),
        ),
    ]
