# Generated by Django 5.1.3 on 2025-01-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_runs", "0002_savedrunningsession_actual_cooldown_pace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrunningsession",
            name="cooldown_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsession",
            name="total_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsession",
            name="warmup_distance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsession",
            name="workout_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
