# Generated by Django 5.1.3 on 2025-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MobilityWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workout_name", models.CharField(max_length=50)),
                ("body_area", models.CharField(blank=True, max_length=15, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=200, null=True)),
                ("number_of_movements", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
