# Generated by Django 5.1.3 on 2024-12-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movements", "0001_initial"),
        ("workout_sections", "0002_alter_section_section_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_order",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "movement_difficulty",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "movement_comment",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_movement_details",
                        to="movements.movement",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_movement_details",
                        to="workout_sections.section",
                    ),
                ),
            ],
        ),
    ]
