# Generated by Django 5.1.3 on 2024-12-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout_section_movement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectionmovement",
            old_name="movement",
            new_name="movements",
        ),
    ]
