# Generated by Django 5.1.3 on 2025-03-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_body_part", models.JSONField(default=dict)),
                ("monthly_body_part", models.JSONField(default=dict)),
                ("yearly_body_part", models.JSONField(default=dict)),
                ("weekly_activity_type", models.JSONField(default=dict)),
                ("monthly_activity_type", models.JSONField(default=dict)),
                ("yearly_activity_type", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
