# Generated by Django 5.1.3 on 2025-01-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conditioning_summary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditioningDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_order",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("exercise", models.CharField(blank=True, max_length=255, null=True)),
                ("detail", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "conditioning_overview",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditioning_details",
                        to="conditioning_summary.conditioningoverview",
                    ),
                ),
            ],
        ),
    ]
