# Generated by Django 5.1.3 on 2025-01-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conditioning_details", "0002_conditioningdetail_movement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditioningdetail",
            name="movement",
        ),
    ]
