# Generated by Django 5.1.3 on 2025-01-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_workouts", "0006_workout_activity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedMobilitySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_movements", models.FloatField(blank=True, null=True)),
                (
                    "session_video",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("rpe", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobility_sessions",
                        to="saved_workouts.workout",
                    ),
                ),
            ],
        ),
    ]
