# Generated by Django 5.1.3 on 2025-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_mobility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedmobilitysession",
            name="session_type",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
