# Generated by Django 5.1.3 on 2025-01-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_run_interval_times", "0001_initial"),
        ("saved_run_intervals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedrunningsplittime",
            name="saved_interval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="split_times",
                to="saved_run_intervals.savedrunninginterval",
            ),
        ),
    ]
