# Generated by Django 5.1.3 on 2025-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_run_interval_times", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedrunningsplittime",
            name="time_in_seconds",
        ),
        migrations.AddField(
            model_name="savedrunningsplittime",
            name="actual_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsplittime",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedrunningsplittime",
            name="target_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
