# Generated by Django 5.1.3 on 2024-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_workouts", "0002_alter_workout_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
