# Generated by Django 5.1.3 on 2024-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_workouts", "0003_alter_workout_scheduled_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
