# Generated by Django 5.1.3 on 2025-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_workouts", "0006_workout_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="workout_code",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
