# Generated by Django 5.1.3 on 2025-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saved_workouts", "0007_workout_workout_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="hyrox_division",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
