# Generated by Django 5.1.3 on 2025-03-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saved_workouts", "0008_workout_hyrox_division"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="hyrox_division",
        ),
    ]
