# Generated by Django 5.1.3 on 2025-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggested_strength_overview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedstrength",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
