# Generated by Django 5.1.3 on 2025-03-08 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saved_equipment_lists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedequipmentfilter",
            unique_together={("owner", "filter_name")},
        ),
    ]
