# Generated by Django 5.1.3 on 2025-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulednotification",
            name="cleared_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
