# Generated by Django 5.1.3 on 2025-03-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_schedulednotification_cleared_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulednotification",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
