# Generated by Django 5.1.3 on 2025-03-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("suggested_strength_overview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedStrengthDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("section_number", models.PositiveIntegerField()),
                ("section_movement", models.PositiveIntegerField()),
                ("exercise", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="suggested_strength_overview.suggestedstrength",
                    ),
                ),
            ],
        ),
    ]
